# Generated by Django 3.1.6 on 2021-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('default', 'DEFAULT'), ('request_solver', 'REQUEST_SOLVER'), ('solver', 'SOLVER')], default='default', max_length=20),
        ),
    ]
