# Generated by Django 3.1.6 on 2021-02-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='грн', max_length=10),
        ),
    ]
