# Generated by Django 3.1.6 on 2021-03-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20210317_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
