# Generated by Django 3.1.6 on 2021-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20210324_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('pending_order', 'PENDING ORDER'), ('order', 'ORDER'), ('pending_send', 'PENDING SEND'), ('sent', 'SENT'), ('pending_received', 'PENDING RECEIVED'), ('received', 'RECEIVED'), ('pending_problem', 'PENDING_PROBLEM'), ('problem', 'PROBLEM'), ('pending_refund', 'PENDING_REFUND'), ('pending_no_refund', 'PENDING_NO_REFUND'), ('refund', 'REFUND_BY_SOLVER'), ('no_refund', 'NO_REFUND_BY_SOLVER')], default='new', max_length=20),
        ),
    ]
